# Generated by Django 3.0.6 on 2020-05-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.ImageField(max_length=255, upload_to='team_images/')),
                ('club_state', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image_url', models.ImageField(max_length=255, upload_to='player_images/')),
                ('jersey_number', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('player_skill', models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('all-rounder', 'All-rounder')], max_length=100)),
                ('total_matches', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('highest_scores', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketapp.Team')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_winner', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_teamname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_teamname', to='cricketapp.Team')),
                ('second_teamname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_teamname', to='cricketapp.Team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
